CREATE TABLE users (	
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar
(50),
email	varchar
(25),
password	varchar
(255)
);

CREATE TABLE providers(	
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar
(255),
email	varchar
(255),
password	varchar
(255),
phone	varchar
(30),
zip varchar(10),
description	text

);


CREATE TABLE messages(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
users_id	INTEGER REFERENCES users
(id) ON
DELETE CASCADE,
providers_id INTEGER REFERENCES providers
(id) ON
DELETE CASCADE NOT NULL,
sender VARCHAR(3),
message_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
message VARCHAR(255)

);